# Generated by Django 3.2.9 on 2021-12-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AddField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(null=True, verbose_name='Стаж'),
        ),
        migrations.AddField(
            model_name='staff',
            name='post',
            field=models.CharField(max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Телефон'),
        ),
    ]
